ssgrid_para = {
    "beijing": {
        "region_num": 900,  # coarse_gra * coarse_gra
        "node_num": 296710,
        "edge_num": 651748,
        # "time_delta": 3600,
        "d_node": 64,
        "d_r": 128,
        "d_m1": 256,
        "d_m2": 512,
        "d_m3": 256,
        "d_m4": 64+256,
        "dropout": 0.2,
        # "epochs": 1000,
        "epochs": 2,
        "batch_size": 1000,
        "lr_base": 1e-3,
        "lr_step": 2,
        "lr_decay": 0.8,
        "clip": 1.0,
        "use_node2vec": True,
        # "use_traffic4key": True,
        # "use_offset": True,
        # "mask_size": 100,
        # "utc": 8,
        "pretrained_node_emb": "nodes_embedding_64.npy",
        "pretrained_region_emb": "region_embedding_64.npy",
        "segs_geo": "segs_geo.npy",
    },
}
