searchsp_para = {
    "beijing": {
        "node_num": 296710,
        "time_delta": 3600,
        "d_seg": 64,
        "d_s": 2 * (64 + 0) + 64 + 3,
        "d_m7": 2048,
        "d_m8": 256,
        "dropout": 0.2,
        # "epochs": 1000,
        "epochs": 2,
        "batch_size": 8192,
        "lr_base": 1e-3,
        "lr_step": 2,
        "lr_decay": 0.8,
        "clip": 1.0,
        "use_node2vec": True,
        "use_traffic4key": True,
        "use_offset": True,
        "mask_size": 100,
        "utc": 8,
        "pretrained_input_emb_path": "nodes_embedding_64.npy",
    },
}
